log_dir: "/Users/danlongpan/goproject/catgin"  #"/var/log"
log_name:
  stat_log_file: "go_info"
  error_log_file: "go_error"
  panic_log_file: "go_panic"
  stderr_panic_log_file: "go_Stderr_panic"
mysql:
  dsn: ""
  database: ""
  username: ""
  password: ""
  port: ""
redis:
  hostname: ""
  port: ""
  database: ""
token_cache: ""